function [Blinkspersecond, ONFitValue, OFFFitValue] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [BLINKSPERSECOND, ONFITVALUE, OFFFITVALUE] = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as column vectors.
%
%  [BLINKSPERSECOND, ONFITVALUE, OFFFITVALUE] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Blinkspersecond, ONFitValue, OFFFitValue] = importfile("C:\Users\wslch\OneDrive - University of Rochester\Krauss Group\Papers\Jen JPCC BKQD\QD + BG data\changepoint\Results.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Jun-2020 21:33:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Blinkspersecond", "ONFitValue", "Var3", "OFFFitValue", "Var5"];
opts.SelectedVariableNames = ["Blinkspersecond", "ONFitValue", "OFFFitValue"];
opts.VariableTypes = ["double", "double", "string", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var5"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Blinkspersecond = tbl.Blinkspersecond;
ONFitValue = tbl.ONFitValue;
OFFFitValue = tbl.OFFFitValue;
end