%% Linear
%F_save = uigetdir(F);
file = fullfile(F_save,'Results.csv');
[blink on off] = getResults(file);
bins = 20;
on_avg = nanmean(on); off_avg = nanmean(off);
figure(10); fig = tiledlayout(2,1);
nexttile;
m_on = histcounts(on,bins);
m_off = histcounts(off,bins);
bar(linspace(min(on),max(on),bins),m_on);
title('m_{on} Values');
legend(['\mu_{on} = ' num2str(on_avg)]);
nexttile;
bar(linspace(min(off),max(off),bins),m_off);
title('m_{off} Values');
legend(['\mu_{off} = ' num2str(off_avg)]);
xlabel(fig,'m'); ylabel(fig,'# Occurences');
arrayfun(@(x) grid(x,'on'), findobj(gcf,'Type','axes'));
img = "Histogram of Power Law Fit Parameter.png"; 
name =  fullfile(F_save,img);
exportgraphics(fig,name);
figure(11);
[blinking, edges] = histcounts(blink,'BinWidth',1);
bar(blinking); legend(['\mu_{blink} = ' num2str(nanmean(blink))]);
title('Average Blink Rates');
xlabel('# Blinks per second (1/s)'); ylabel('# Occurences');
img2 = "Histogram of Blink Rates.png";
name2 = fullfile(F_save,img2);
exportgraphics(figure(11),name2);
%% NonLinear
% file = fullfile(F,'Results-NonLinearFit.csv');
% [on off] = getFits(file);
% bins = 20;
% figure(1); fig = tiledlayout(2,1);
% nexttile;
% m_on = histcounts(on,bins);
% m_off = histcounts(off,bins);
% bar(linspace(min(on),max(on),bins),m_on);
% title('m_{on} Values');
% nexttile;
% bar(linspace(min(off),max(off),bins),m_off);
% title('m_{off} Values');
% xlabel(fig,'m'); ylabel(fig,'# Occurences');
% arrayfun(@(x) grid(x,'on'), findobj(gcf,'Type','axes'));
% img = "Histogram of Power Law Fit Parameter.png"; 
% name =  fullfile(F,'figures-NL',img);
% exportgraphics(fig,name);